apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  my.cnf: |
    [mysqld]
    server-id=1
    log-bin=mysql-bin
    binlog-format=ROW
    gtid-mode=ON
    enforce-gtid-consistency=ON
    master-info-repository=TABLE
    relay-log-info-repository=TABLE
    log-slave-updates=ON
    read-only=OFF
